version: 2
project_name: suluctl

builds:
  - main: .
    binary: suluctl
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

dockers:
  - image_templates:
      - ghcr.io/ellyzz/suluctl:{{ .Version }}
      - ghcr.io/ellyzz/suluctl:latest
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64

changelog:
  use: github-native
